version: "2"

linters:
  default: standard
  enable:
    - gocyclo
    - goconst
    - misspell
    - unconvert
    - unparam
    - gosec
    - prealloc

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  gosec:
    excludes:
      - G104 # Audit errors not checked (allow for deferred closes)

issues:
  exclude-rules:
    # Exclude some linters from running on tests
    - path: _test\.go
      linters:
        - gosec
        - unparam
