package phases

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/inc4/gonka-nop/internal/config"
	"github.com/inc4/gonka-nop/internal/ui"
)

// ConfigGeneration generates configuration files
type ConfigGeneration struct{}

func NewConfigGeneration() *ConfigGeneration {
	return &ConfigGeneration{}
}

func (p *ConfigGeneration) Name() string {
	return "Configuration"
}

func (p *ConfigGeneration) Description() string {
	return "Generating node configuration files"
}

func (p *ConfigGeneration) ShouldRun(state *config.State) bool {
	return !state.IsPhaseComplete(p.Name())
}

func (p *ConfigGeneration) Run(ctx context.Context, state *config.State) error {
	// Get public IP
	publicIP, err := ui.Input("Enter your server's public IP address:", "")
	if err != nil {
		return err
	}
	state.PublicIP = publicIP

	// Get HuggingFace home directory
	defaultHFHome := "/mnt/shared/huggingface"
	hfHome, err := ui.Input("HuggingFace cache directory:", defaultHFHome)
	if err != nil {
		return err
	}
	state.HFHome = hfHome

	// Create output directory
	err = ui.WithSpinner("Creating output directory", func() error {
		return os.MkdirAll(state.OutputDir, 0755)
	})
	if err != nil {
		return err
	}

	// Generate config.env
	err = ui.WithSpinner("Generating config.env", func() error {
		time.Sleep(300 * time.Millisecond)
		return generateConfigEnv(state)
	})
	if err != nil {
		return err
	}
	ui.Detail("Created: %s/config.env", state.OutputDir)

	// Generate node-config.json
	err = ui.WithSpinner("Generating node-config.json", func() error {
		time.Sleep(300 * time.Millisecond)
		return generateNodeConfig(state)
	})
	if err != nil {
		return err
	}
	ui.Detail("Created: %s/node-config.json", state.OutputDir)

	// Generate docker-compose.yml
	err = ui.WithSpinner("Generating docker-compose.yml", func() error {
		time.Sleep(300 * time.Millisecond)
		return generateDockerCompose(state)
	})
	if err != nil {
		return err
	}
	ui.Detail("Created: %s/docker-compose.yml", state.OutputDir)

	// Generate docker-compose.mlnode.yml
	err = ui.WithSpinner("Generating docker-compose.mlnode.yml", func() error {
		time.Sleep(300 * time.Millisecond)
		return generateMLNodeCompose(state)
	})
	if err != nil {
		return err
	}
	ui.Detail("Created: %s/docker-compose.mlnode.yml", state.OutputDir)

	ui.Success("All configuration files generated")
	return nil
}

func generateConfigEnv(state *config.State) error {
	content := fmt.Sprintf(`# Gonka Node Configuration
# Generated by gonka-nop

# Identity
KEY_NAME=%s
KEYRING_PASSWORD=changeme
ACCOUNT_PUBKEY=%s

# Network
PUBLIC_URL=http://%s:8000
P2P_EXTERNAL_ADDRESS=tcp://%s:%d
API_PORT=%d

# Seed nodes
SEED_API_URL=http://node2.gonka.ai:8000
SEED_NODE_RPC_URL=http://node2.gonka.ai:26657
SEED_NODE_P2P_URL=tcp://node2.gonka.ai:5000

# Internal routing
DAPI_API__POC_CALLBACK_URL=http://api:9100
DAPI_CHAIN_NODE__URL=http://node:26657

# ML Node
HF_HOME=%s
PORT=8080
INFERENCE_PORT=5050
NODE_CONFIG=./node-config.json

# Sync
SYNC_WITH_SNAPSHOTS=true
TRUSTED_BLOCK_PERIOD=2000
`,
		state.KeyName,
		state.AccountPubKey,
		state.PublicIP,
		state.PublicIP,
		state.P2PPort,
		state.APIPort,
		state.HFHome,
	)

	return os.WriteFile(filepath.Join(state.OutputDir, "config.env"), []byte(content), 0600)
}

func generateNodeConfig(state *config.State) error {
	// Generate vLLM args based on TP/PP
	args := []string{"--quantization", "fp8", "--gpu-memory-utilization", "0.9"}
	if state.TPSize > 1 {
		args = append(args, fmt.Sprintf("--tensor-parallel-size %d", state.TPSize))
	}
	if state.PPSize > 1 {
		args = append(args, fmt.Sprintf("--pipeline-parallel-size %d", state.PPSize))
	}

	content := fmt.Sprintf(`{
  "models": {
    "%s": {
      "args": ["%s"]
    }
  }
}
`, state.SelectedModel, joinArgs(args))

	return os.WriteFile(filepath.Join(state.OutputDir, "node-config.json"), []byte(content), 0644)
}

func joinArgs(args []string) string {
	result := ""
	for i, arg := range args {
		if i > 0 {
			result += "\", \""
		}
		result += arg
	}
	return result
}

func generateDockerCompose(state *config.State) error {
	content := `# Gonka Node Docker Compose
# Generated by gonka-nop

version: "3.8"

services:
  tmkms:
    image: ghcr.io/product-science/tmkms-softsign-with-keygen:v0.2.7-post1
    restart: unless-stopped
    volumes:
      - ./tmkms:/tmkms
    env_file:
      - config.env

  node:
    image: ghcr.io/product-science/inferenced:v0.2.7-post1
    restart: unless-stopped
    depends_on:
      - tmkms
    ports:
      - "5000:5000"
      - "26657:26657"
    volumes:
      - ./node-data:/root/.inferenced
    env_file:
      - config.env

  api:
    image: ghcr.io/product-science/api:v0.2.7-post1
    restart: unless-stopped
    depends_on:
      - node
    ports:
      - "9100:9100"
      - "9200:9200"
    env_file:
      - config.env

  bridge:
    image: ghcr.io/product-science/bridge:v0.2.7-post1
    restart: unless-stopped
    depends_on:
      - node
    env_file:
      - config.env

  proxy:
    image: ghcr.io/product-science/proxy:v0.2.7-post1
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "8000:8000"
    env_file:
      - config.env

  explorer:
    image: ghcr.io/product-science/explorer:v0.2.7-post1
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "3000:3000"
    env_file:
      - config.env
`
	return os.WriteFile(filepath.Join(state.OutputDir, "docker-compose.yml"), []byte(content), 0644)
}

func generateMLNodeCompose(state *config.State) error {
	content := fmt.Sprintf(`# Gonka ML Node Docker Compose
# Generated by gonka-nop

version: "3.8"

services:
  mlnode:
    image: ghcr.io/product-science/mlnode:3.0.11-post1
    restart: unless-stopped
    ipc: host
    environment:
      - HF_HOME=%s
      - VLLM_ATTENTION_BACKEND=FLASHINFER
    volumes:
      - %s:/root/.cache
      - ./node-config.json:/app/node-config.json
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: uvicorn api.app:app --host=0.0.0.0 --port=8080
    ports:
      - "8080:8080"
      - "5050:5050"
    env_file:
      - config.env
`, state.HFHome, state.HFHome)

	return os.WriteFile(filepath.Join(state.OutputDir, "docker-compose.mlnode.yml"), []byte(content), 0644)
}
